language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21

android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support

script: ./gradlew assembleDebug
